<?php
// Register Custom Post Type for Audio
function aap_register_audio_post_type() {
    $labels = array(
        'name'                  => _x( 'Audio Samples', 'Post Type General Name', 'text_domain' ),
        'singular_name'         => _x( 'Audio Sample', 'Post Type Singular Name', 'text_domain' ),
        'menu_name'             => __( 'Audio Samples', 'text_domain' ),
        'name_admin_bar'        => __( 'Audio Sample', 'text_domain' ),
        'archives'              => __( 'Audio Archives', 'text_domain' ),
        'attributes'            => __( 'Audio Attributes', 'text_domain' ),
        'parent_item_colon'     => __( 'Parent Audio:', 'text_domain' ),
        'all_items'             => __( 'All Audio Samples', 'text_domain' ),
        'add_new_item'          => __( 'Add New Audio Sample', 'text_domain' ),
        'add_new'               => __( 'Add New', 'text_domain' ),
        'new_item'              => __( 'New Audio Sample', 'text_domain' ),
        'edit_item'             => __( 'Edit Audio Sample', 'text_domain' ),
        'update_item'           => __( 'Update Audio Sample', 'text_domain' ),
        'view_item'             => __( 'View Audio Sample', 'text_domain' ),
        'view_items'            => __( 'View Audio Samples', 'text_domain' ),
        'search_items'          => __( 'Search Audio Sample', 'text_domain' ),
        'not_found'             => __( 'Not found', 'text_domain' ),
        'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
        'featured_image'        => __( 'Featured Image', 'text_domain' ),
        'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
        'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
        'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
        'insert_into_item'      => __( 'Insert into audio sample', 'text_domain' ),
        'uploaded_to_this_item' => __( 'Uploaded to this audio sample', 'text_domain' ),
        'items_list'            => __( 'Audio samples list', 'text_domain' ),
        'items_list_navigation' => __( 'Audio samples list navigation', 'text_domain' ),
        'filter_items_list'     => __( 'Filter audio samples list', 'text_domain' ),
    );
    $args = array(
        'label'                 => __( 'Audio Sample', 'text_domain' ),
        'description'           => __( 'A post type for audio samples.', 'text_domain' ),
        'labels'                => $labels,
        'supports'              => array( 'title' ),
        'taxonomies'            => array(),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 5,
        'menu_icon'             => 'dashicons-format-audio',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => true,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type( 'audio_sample', $args );
}
add_action( 'init', 'aap_register_audio_post_type', 0 );
